name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: npm install

      - run: npm publish --otp=1b389c8f92cf4e601e2339c430c05afe23485fd6eee71f9b6fc567e65644317b
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
